openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
- url: http://localhost:8084
  description: Generated server url
paths:
  /api/videojuego/{id}:
    put:
      tags:
      - video-juego-controller
      summary: Actualizar un videojuego por ID
      operationId: actualizarVideoJuego
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoJuego'
        required: true
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        "404":
          description: No existe videojuego con el ID proporcionado
        "200":
          description: Videojuego actualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoJuego'
    delete:
      tags:
      - video-juego-controller
      summary: Eliminar un videojuego por ID
      operationId: eliminarVideoJuego
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        "204":
          description: Videojuego eliminado
  /api/videojuego:
    get:
      tags:
      - video-juego-controller
      summary: Obtener una lista de todos los videojuegos
      operationId: obtenerVideoJuegos
      responses:
        "409":
          description: Conflict
          content:
            '*/*':
              schema:
                type: string
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        "200":
          description: Lista de videojuegos registrados
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoJuego'
    post:
      tags:
      - video-juego-controller
      summary: Registrar Videojuego
      operationId: registrarVideoJuego
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/VideoJuego'
        required: true
      responses:
        "409":
          description: Ya existe un videojuego con el nombre especificado
          content: {}
        "400":
          description: Bad Request
          content:
            '*/*':
              schema:
                type: string
        "201":
          description: Videojuego Registrado Exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VideoJuego'
components:
  schemas:
    VideoJuego:
      required:
      - nombre
      type: object
      properties:
        id:
          type: string
        nombre:
          type: string
        genero:
          type: string
        clasificación:
          type: string
