apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: tekton-event-listener
spec:
  serviceAccountName: tekton-pipeline
  namespaceSelector:
    matchNames:
    - user17
  triggers:
    - name: github-listener
    # - name: github-listener
    #   interceptors:
    #     - github:
    #         secretRef:
    #           secretName: github-secret
    #           secretKey: secretToken
    #         eventTypes:
    #           - pull_request
    #     - cel:
    #         filter: "body.action in ['opened', 'synchronize', 'reopened']"
      bindings:
        - ref: tekton-trigger-binding
      template:
        ref: tekton-trigger-template